import type { AgentChannel, AgentMessage, AgentRecord, MessageBusState, MessageKind, WitnessEvent } from "./types";

const ALL_KINDS: MessageKind[] = [
  "bulletin",
  "handoff",
  "task",
  "question",
  "answer",
  "alert",
  "decision",
  "artifact",
  "canon_update",
  "security_review",
  "build_report",
  "test_report",
];

export const MESSAGEBUS_CHANNELS: AgentChannel[] = [
  {
    id: "#system_announcements",
    name: "System Announcements",
    purpose: "Boletines generales del DUAT Telecom Core.",
    visibility: "system",
    allowed_kinds: ["bulletin", "alert", "decision"],
    retention_policy: "project",
  },
  {
    id: "#handoffs",
    name: "Handoffs",
    purpose: "Transferencias de contexto entre agentes con fingerprint.",
    visibility: "team",
    allowed_kinds: ["handoff", "question", "answer"],
    retention_policy: "permanent",
  },
  {
    id: "#witnesslog",
    name: "WitnessLog",
    purpose: "Eventos append-only con hash y evidencia.",
    visibility: "system",
    allowed_kinds: ["decision", "build_report", "test_report", "artifact"],
    retention_policy: "permanent",
  },
  {
    id: "#tasks",
    name: "Task Queue",
    purpose: "Tareas activas, bloqueos y cierres verificables.",
    visibility: "team",
    allowed_kinds: ["task", "question", "answer", "decision"],
    retention_policy: "project",
  },
  {
    id: "#security_review",
    name: "Security Review",
    purpose: "Alertas y revisiones de credenciales, privacidad y publicacion.",
    visibility: "system",
    allowed_kinds: ["security_review", "alert", "task"],
    retention_policy: "permanent",
  },
  {
    id: "#canon_updates",
    name: "Canon Updates",
    purpose: "Cambios de canon, fronteras epistemicas y mapas de continuidad.",
    visibility: "team",
    allowed_kinds: ["canon_update", "decision", "artifact"],
    retention_policy: "permanent",
  },
  {
    id: "#build_reports",
    name: "Build Reports",
    purpose: "Compilacion, pruebas y resultados de validacion local.",
    visibility: "team",
    allowed_kinds: ["build_report", "test_report", "artifact"],
    retention_policy: "project",
  },
  {
    id: "#research",
    name: "Research",
    purpose: "Investigacion y comparaciones sin exponer canon privado completo.",
    visibility: "team",
    allowed_kinds: ["question", "answer", "artifact", "canon_update"],
    retention_policy: "project",
  },
  {
    id: "#lovable_ui",
    name: "Lovable UI",
    purpose: "Superficie React/Lovable, rutas, HUD y estado visual.",
    visibility: "team",
    allowed_kinds: ["task", "build_report", "artifact"],
    retention_policy: "project",
  },
  {
    id: "#codex_runs",
    name: "Codex Runs",
    purpose: "Corridas Codex, evidence packs y handoffs.",
    visibility: "team",
    allowed_kinds: ["handoff", "test_report", "build_report", "decision"],
    retention_policy: "permanent",
  },
  {
    id: "#claudio_local",
    name: "Claudio Local",
    purpose: "Operador local Claudio, COMMS y runtime no-publico.",
    visibility: "private",
    allowed_kinds: ["task", "handoff", "security_review", "build_report"],
    retention_policy: "project",
  },
  {
    id: "#wabi_sabi_orchestration",
    name: "Wabi-Sabi Orchestration",
    purpose: "Orquestacion local, planes y rutas no destructivas.",
    visibility: "private",
    allowed_kinds: ["task", "handoff", "decision", "artifact"],
    retention_policy: "project",
  },
  {
    id: "#duat_product",
    name: "DUAT Product",
    purpose: "Producto DUAT, UX, paquetes y roadmap local.",
    visibility: "team",
    allowed_kinds: ALL_KINDS,
    retention_policy: "project",
  },
];

export const MESSAGEBUS_AGENTS: AgentRecord[] = [
  {
    id: "wabi_sabi_orchestrator",
    name: "Wabi-Sabi Orchestrator",
    role: "Coordina rutas locales y evita apertura de trabajo sin cierre.",
    status: "working",
    capabilities: ["orchestration", "local_policy", "handoff"],
    allowed_channels: ["#wabi_sabi_orchestration", "#handoffs", "#tasks", "#codex_runs"],
    current_task_id: "work-run2-telecom-core",
  },
  {
    id: "cerebro_canon",
    name: "CEREBRO Canon",
    role: "Custodia canon, evidencia y fronteras epistemicas.",
    status: "reviewing",
    capabilities: ["canon", "claim_boundary", "indexing"],
    allowed_channels: ["#canon_updates", "#research", "#handoffs"],
  },
  {
    id: "claudio_local_operator",
    name: "Claudio Local Operator",
    role: "Opera superficies locales Claudio sin publicacion externa.",
    status: "idle",
    capabilities: ["runtime", "comms", "witnesslog"],
    allowed_channels: ["#claudio_local", "#witnesslog", "#handoffs"],
  },
  {
    id: "codex_engineer",
    name: "Codex Engineer",
    role: "Implementa, prueba y deja artefactos verificables.",
    status: "working",
    capabilities: ["typescript", "docs", "tests"],
    allowed_channels: ["#codex_runs", "#build_reports", "#tasks", "#lovable_ui"],
    current_task_id: "work-run2-telecom-core",
  },
  {
    id: "lovable_frontend",
    name: "Lovable Frontend",
    role: "Mantiene la pantalla DUAT y la UX del HUD.",
    status: "working",
    capabilities: ["react", "vite", "hud_ui"],
    allowed_channels: ["#lovable_ui", "#duat_product", "#build_reports"],
  },
  {
    id: "security_gate",
    name: "Security Gate",
    role: "Bloquea credenciales, deploy, push y publicacion no aprobada.",
    status: "blocked",
    capabilities: ["safety_scan", "action_gate", "publication_block"],
    allowed_channels: ["#security_review", "#system_announcements", "#witnesslog"],
  },
  {
    id: "research_scout",
    name: "Research Scout",
    role: "Compara frameworks y traduce patrones externos a MEDIOEVO.",
    status: "reviewing",
    capabilities: ["framework_research", "mcp", "a2a"],
    allowed_channels: ["#research", "#canon_updates", "#duat_product"],
  },
  {
    id: "duat_product_designer",
    name: "DUAT Product Designer",
    role: "Define producto, paneles y UX operacional.",
    status: "idle",
    capabilities: ["product", "ux", "release_boundary"],
    allowed_channels: ["#duat_product", "#lovable_ui", "#tasks"],
  },
  {
    id: "lore_archivist",
    name: "Lore Archivist",
    role: "Protege material editorial y privado fuera de releases tecnicos.",
    status: "idle",
    capabilities: ["archive", "private_boundary", "provenance"],
    allowed_channels: ["#canon_updates", "#research", "#security_review"],
  },
  {
    id: "human_operator",
    name: "Human Operator",
    role: "Autoridad humana para revisiones, credenciales, limpieza y publicacion.",
    status: "idle",
    capabilities: ["approve_review", "policy", "final_gate"],
    allowed_channels: MESSAGEBUS_CHANNELS.map((channel) => channel.id),
  },
];

export const MESSAGEBUS_MESSAGES: AgentMessage[] = [
  {
    id: "msg-run2-bulletin-001",
    thread_id: "thread-run2-telecom",
    channel_id: "#system_announcements",
    from_agent: "codex_engineer",
    to_agents: ["human_operator", "wabi_sabi_orchestrator", "lovable_frontend"],
    kind: "bulletin",
    priority: "P1",
    status: "delivered",
    title: "DUAT Telecom Core Run 2 activo",
    body: "El handoff estatico pasa a MessageBus local con bulletin, inbox/outbox, canales, WitnessLog y consola.",
    certeza: ["Run 1 existe y tiene safety scan con hallazgos enmascarados.", "No hay backend externo ni credenciales."],
    inferencia: ["La UI React disponible puede alojar /telecom como consola mock."],
    incognita: ["El ZIP reconstructivo v12.2.1 queda en SECURITY_REVIEW y no se extrae."],
    bloqueo: ["No deploy, no publicacion, no limpieza."],
    action_required: "Validar build/test local y revisar el reporte Run 2.",
    evidence_refs: ["MEDIOEVO_LIVE_TREE/TEST_REPORT.md", "MEDIOEVO_LIVE_TREE/10_QUALITY/SECRET_SCAN_REPORT.md"],
    artifact_refs: ["MEDIOEVO_LIVE_TREE/03_SYSTEMS/DUAT_TELECOM_CORE.md"],
    witness_event_ids: ["wit-run2-start"],
    R_estimado: 0.28,
    Phi_eff: 0.72,
    created_at: "2026-05-12T08:00:00.000Z",
    updated_at: "2026-05-12T08:00:00.000Z",
    ack_by: ["codex_engineer"],
    hash: "h-275cf3e3",
  },
  {
    id: "msg-run2-p0-security-001",
    thread_id: "thread-run2-security",
    channel_id: "#security_review",
    from_agent: "security_gate",
    to_agents: ["human_operator", "codex_engineer"],
    kind: "security_review",
    priority: "P0",
    status: "blocked",
    title: "Publicacion bloqueada por safety scan",
    body: "Run 1 reporta 475 hallazgos enmascarados. El bus puede operar localmente, pero push/deploy/publicacion quedan bloqueados.",
    certeza: ["10_QUALITY/SECRET_SCAN_REPORT.md reporta BLOQUEO_PUBLICACION TRUE.", "Los valores estan redactados."],
    inferencia: ["El bloqueo no impide docs, tests ni UI local."],
    incognita: ["No hay allowlist especifica para un release Telecom Core."],
    bloqueo: ["No push.", "No deploy.", "No publicacion."],
    action_required: "Mantener ActionGate en REVIEW/BLOCK para externos.",
    evidence_refs: ["MEDIOEVO_LIVE_TREE/10_QUALITY/SECRET_SCAN_REPORT.md"],
    artifact_refs: [],
    witness_event_ids: ["wit-run2-security"],
    R_estimado: 0.42,
    Phi_eff: 0.66,
    created_at: "2026-05-12T08:04:00.000Z",
    updated_at: "2026-05-12T08:04:00.000Z",
    ack_by: ["security_gate"],
    hash: "h-a0a79e39",
    prev_hash: "h-275cf3e3",
  },
  {
    id: "msg-run2-handoff-001",
    thread_id: "thread-run2-telecom",
    channel_id: "#handoffs",
    from_agent: "wabi_sabi_orchestrator",
    to_agents: ["codex_engineer", "lovable_frontend"],
    kind: "handoff",
    priority: "P1",
    status: "sent",
    title: "Handoff hacia bus vivo",
    body: "Convertir artefactos estaticos de continuidad en canales consultables por agente.",
    certeza: ["Run 1 ya creo fingerprint y NEXT_SESSION_BRIEF."],
    inferencia: ["La cola de tareas debe vivir como mensajes con evidencia, no como chat suelto."],
    incognita: ["Backend real pendiente."],
    bloqueo: ["Sin backend externo ni red."],
    evidence_refs: ["MEDIOEVO_LIVE_TREE/NEXT_SESSION_BRIEF.md"],
    artifact_refs: ["MEDIOEVO_LIVE_TREE/03_SYSTEMS/MEDIOEVO_MESSAGEBUS.md"],
    handoff_fingerprint: "MDV-TELECOM-RUN2-6C9A",
    witness_event_ids: ["wit-run2-handoff"],
    R_estimado: 0.26,
    Phi_eff: 0.74,
    created_at: "2026-05-12T08:08:00.000Z",
    updated_at: "2026-05-12T08:08:00.000Z",
    ack_by: [],
    hash: "h-92149a5a",
    prev_hash: "h-a0a79e39",
  },
  {
    id: "msg-run2-work-001",
    thread_id: "thread-run2-telecom",
    channel_id: "#tasks",
    from_agent: "codex_engineer",
    to_agents: ["lovable_frontend"],
    kind: "task",
    priority: "P1",
    status: "queued",
    title: "Implementar consola /telecom",
    body: "Mostrar Latest Bulletin, inbox/outbox, canales, handoffs, WitnessLog, P0, tareas, canon, seguridad y artefactos.",
    certeza: ["Vite/React existe y es private."],
    inferencia: ["Una ruta local basta para Run 2."],
    incognita: ["No hay router instalado."],
    bloqueo: ["No instalar dependencias nuevas."],
    evidence_refs: ["public release Vite/React package.json verified locally"],
    artifact_refs: ["src/ui/TelecomCore.tsx"],
    witness_event_ids: [],
    R_estimado: 0.24,
    Phi_eff: 0.76,
    created_at: "2026-05-12T08:12:00.000Z",
    updated_at: "2026-05-12T08:12:00.000Z",
    ack_by: [],
    hash: "h-6cf06c2a",
    prev_hash: "h-92149a5a",
  },
  {
    id: "msg-run2-canon-001",
    thread_id: "thread-run2-canon",
    channel_id: "#canon_updates",
    from_agent: "cerebro_canon",
    to_agents: ["codex_engineer", "research_scout"],
    kind: "canon_update",
    priority: "P2",
    status: "delivered",
    title: "Canon v12.2.1 tratado como SECURITY_REVIEW",
    body: "La ruta visible es ZIP reconstructivo; no se extrae ni se usa como runtime vivo hasta revision.",
    certeza: ["Source cards registran la ruta y estado SECURITY_REVIEW."],
    inferencia: ["El bus debe referenciarlo por evidencia, no absorberlo."],
    incognita: ["Contenido interno no inspeccionado."],
    bloqueo: ["No extraer ZIP grande."],
    evidence_refs: ["MEDIOEVO_LIVE_TREE/01_SOURCE_CARDS/SECURITY_REVIEW-006-MEDIOEVO-OSIT-V12-2-1-CARPETA-MAESTRA-RE.md"],
    artifact_refs: ["MEDIOEVO_LIVE_TREE/03_SYSTEMS/AGENT_MESSAGE_SCHEMA.md"],
    witness_event_ids: [],
    R_estimado: 0.31,
    Phi_eff: 0.69,
    created_at: "2026-05-12T08:16:00.000Z",
    updated_at: "2026-05-12T08:16:00.000Z",
    ack_by: ["cerebro_canon"],
    hash: "h-f0fc80b3",
    prev_hash: "h-6cf06c2a",
  },
  {
    id: "msg-run2-artifact-001",
    thread_id: "thread-run2-artifacts",
    channel_id: "#build_reports",
    from_agent: "codex_engineer",
    to_agents: ["human_operator", "wabi_sabi_orchestrator"],
    kind: "artifact",
    priority: "P2",
    status: "delivered",
    title: "Artifact Registry inicial",
    body: "Registro mock apunta a documentos de arquitectura, tests y export JSON/Markdown del bus.",
    certeza: ["Los artefactos se generan en rutas locales."],
    inferencia: ["El registry puede migrar a backend real despues."],
    incognita: ["No hay firma ni versionado remoto."],
    bloqueo: ["No publicar registry."],
    evidence_refs: ["MEDIOEVO_LIVE_TREE/03_SYSTEMS/MEDIOEVO_MESSAGEBUS.md"],
    artifact_refs: ["exportMessageBusJson()", "exportBulletinMarkdown()"],
    witness_event_ids: [],
    R_estimado: 0.22,
    Phi_eff: 0.78,
    created_at: "2026-05-12T08:20:00.000Z",
    updated_at: "2026-05-12T08:20:00.000Z",
    ack_by: [],
    hash: "h-bcb9fd7a",
    prev_hash: "h-f0fc80b3",
  },
];

export const MESSAGEBUS_WITNESS_EVENTS: WitnessEvent[] = [
  {
    id: "wit-run2-start",
    actor: "codex_engineer",
    action: "read_run1_reports",
    result: "all_requested_run1_files_present",
    R_before: 0.34,
    R_after: 0.3,
    evidence_refs: ["MEDIOEVO_LIVE_TREE/00_START_HERE/LIVE_TREE_STATUS_RUN_2.md"],
    created_at: "2026-05-12T08:00:00.000Z",
    hash: "w-8f3b00a5",
  },
  {
    id: "wit-run2-security",
    actor: "security_gate",
    action: "enforce_publication_block",
    result: "external_actions_blocked",
    R_before: 0.3,
    R_after: 0.28,
    evidence_refs: ["MEDIOEVO_LIVE_TREE/10_QUALITY/SECRET_SCAN_REPORT.md"],
    created_at: "2026-05-12T08:04:00.000Z",
    prev_hash: "w-8f3b00a5",
    hash: "w-09a1a151",
  },
  {
    id: "wit-run2-handoff",
    actor: "wabi_sabi_orchestrator",
    action: "handoff_to_messagebus",
    result: "handoff_stream_initialized",
    R_before: 0.28,
    R_after: 0.26,
    evidence_refs: ["MEDIOEVO_LIVE_TREE/NEXT_SESSION_BRIEF.md"],
    created_at: "2026-05-12T08:08:00.000Z",
    prev_hash: "w-09a1a151",
    hash: "w-f94aa22b",
  },
];

export function createInitialMessageBusState(): MessageBusState {
  return {
    agents: MESSAGEBUS_AGENTS.map((agent) => ({ ...agent, capabilities: [...agent.capabilities], allowed_channels: [...agent.allowed_channels] })),
    channels: MESSAGEBUS_CHANNELS.map((channel) => ({ ...channel, allowed_kinds: [...channel.allowed_kinds] })),
    messages: MESSAGEBUS_MESSAGES.map((message) => ({
      ...message,
      to_agents: [...message.to_agents],
      cc_agents: message.cc_agents ? [...message.cc_agents] : undefined,
      certeza: [...message.certeza],
      inferencia: [...message.inferencia],
      incognita: [...message.incognita],
      bloqueo: [...message.bloqueo],
      evidence_refs: [...message.evidence_refs],
      artifact_refs: [...message.artifact_refs],
      witness_event_ids: [...message.witness_event_ids],
      ack_by: [...message.ack_by],
    })),
    witness_events: MESSAGEBUS_WITNESS_EVENTS.map((event) => ({ ...event, evidence_refs: [...event.evidence_refs] })),
  };
}
